<?php

/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Associations;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Layout\FileLayout;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Component\Content\Administrator\Extension\ContentComponent;
use Joomla\Component\Content\Site\Helper\RouteHelper;
use Joomla\CMS\Helper\ModuleHelper;

/** @var \Joomla\Component\Content\Site\View\Article\HtmlView $this */
// Create shortcuts to some parameters.
$params  = $this->item->params;
$canEdit = $params->get('access-edit');
$user    = $this->getCurrentUser();
$info    = $params->get('info_block_position', 0);
$htag    = $this->params->get('show_page_heading') ? 'h2' : 'h1';

// Fetch modules for a position
$mods       = ModuleHelper::getModules('content-bottom');
$modsBanner = ModuleHelper::getModules('content-bottom-banner');

// Check if associations are implemented. If they are, define the parameter.
$assocParam        = (Associations::isEnabled() && $params->get('show_associations'));
$currentDate       = Factory::getDate()->format('Y-m-d H:i:s');
$isNotPublishedYet = $this->item->publish_up > $currentDate;
$isExpired         = !is_null($this->item->publish_down) && $this->item->publish_down < $currentDate;

// Add a full-width flag once and reuse it for both lead and intro items.
$pageClass     = (string) ($this->params->get('pageclass_sfx') ?? '');
$isFullLayout  = (bool) preg_match('/(?:^|\s)full-width(?:\s|$)/', $pageClass);
if ($isFullLayout) { $params->set('fullwidth', 1); }

// Root wrapper: kill horizontal padding on full-width pages
$rootClass = 'com-content-article item-page' . ($isFullLayout ? ' container-fluid px-0' : '');

?>

<div class="<?= $rootClass ?> <?php echo !$isFullLayout ? $this->pageclass_sfx : ''; ?>">
    <div class="blog-items">
        <div class="blog-item bg-body position-relative mb-3">

        <?php // The hero image ?>
        <?php echo LayoutHelper::render('joomla.content.intro_image_article', $this->item); ?>

            <div class="item-content pb-3 px-27 lh-lg">
        <meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? Factory::getApplication()->get('language') : $this->item->language; ?>">
        <?php if ($this->params->get('show_page_heading')) : ?>
        <div class="page-header">
            <h1> <?php echo $this->escape($this->params->get('page_heading')); ?> </h1>
        </div>
        <?php endif;
        if (!empty($this->item->pagination) && !$this->item->paginationposition && $this->item->paginationrelative) {
            echo $this->item->pagination;
        }
        ?>

        <?php $useDefList = $params->get('show_modify_date') || $params->get('show_publish_date') || $params->get('show_create_date')
        || $params->get('show_hits') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author') || $assocParam; ?>

        <?php if ($params->get('show_title')) : ?>
            <<?php echo $htag; ?> class="pb-1 lh-base <?php echo $isFullLayout ? 'fw-bold fs-16 text-center' : 'fw-medium fs-2 text-justify'?>">
                <a class="text-decoration-none" href="<?php echo Route::_(RouteHelper::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language)); ?>">
                    <?php echo $this->escape($this->item->title); ?>
                </a>
            </<?php echo $htag; ?>>
            <?php if ($this->item->state == ContentComponent::CONDITION_UNPUBLISHED) : ?>
                <span class="badge bg-warning text-light"><?php echo Text::_('JUNPUBLISHED'); ?></span>
            <?php endif; ?>
            <?php if ($isNotPublishedYet) : ?>
                <span class="badge bg-warning text-light"><?php echo Text::_('JNOTPUBLISHEDYET'); ?></span>
            <?php endif; ?>
            <?php if ($isExpired) : ?>
                <span class="badge bg-warning text-light"><?php echo Text::_('JEXPIRED'); ?></span>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($canEdit) : ?>
            <?php echo LayoutHelper::render('joomla.content.icons', ['params' => $params, 'item' => $this->item]); ?>
        <?php endif; ?>

        <?php // Content is generated by content plugin event "onContentAfterTitle" ?>
        <?php echo $this->item->event->afterDisplayTitle; ?>

        <?php if ($useDefList && ($info == 0 || $info == 2)) : ?>
            <?php echo LayoutHelper::render('joomla.content.info_block', ['item' => $this->item, 'params' => $params, 'position' => 'above']); ?>
        <?php endif; ?>

        <?php if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
            <?php $this->item->tagLayout = new FileLayout('joomla.content.tags'); ?>

            <?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
        <?php endif; ?>

        <?php // Content is generated by content plugin event "onContentBeforeDisplay"
              // disabled the Jlex ingration comment link ?>
        <?php //echo $this->item->event->beforeDisplayContent; ?>

        <?php if ((int) $params->get('urls_position', 0) === 0) : ?>
            <?php echo $this->loadTemplate('links'); ?>
        <?php endif; ?>
        <?php if ($params->get('access-view')) : ?>
            <?php echo LayoutHelper::render('joomla.content.full_image', $this->item); ?>
            <?php
            if (!empty($this->item->pagination) && !$this->item->paginationposition && !$this->item->paginationrelative) :
                echo $this->item->pagination;
            endif;
            ?>
            <?php if (isset($this->item->toc)) :
                echo $this->item->toc;
            endif; ?>
        <div class="com-content-article__body text-justify">
            <?php echo $this->item->text; ?>
        </div>

            <?php if ($info == 1 || $info == 2) : ?>
                <?php if ($useDefList) : ?>
                    <?php echo LayoutHelper::render('joomla.content.info_block', ['item' => $this->item, 'params' => $params, 'position' => 'below']); ?>
                <?php endif; ?>
                <?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
                    <?php $this->item->tagLayout = new FileLayout('joomla.content.tags'); ?>
                    <?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
                <?php endif; ?>
            <?php endif; ?>

            <?php
            if (!empty($this->item->pagination) && $this->item->paginationposition && !$this->item->paginationrelative) :
                echo $this->item->pagination;
                ?>
            <?php endif; ?>
            <?php if ((int) $params->get('urls_position', 0) === 1) : ?>
                <?php echo $this->loadTemplate('links'); ?>
            <?php endif; ?>
            <?php // Optional teaser intro text for guests ?>
        <?php elseif ($params->get('show_noauth') == true && $user->guest) : ?>
            <?php echo LayoutHelper::render('joomla.content.intro_image', $this->item); ?>
            <?php echo HTMLHelper::_('content.prepare', $this->item->introtext); ?>
            <?php // Optional link to let them register to see the whole article. ?>
            <?php if ($params->get('show_readmore') && $this->item->fulltext != null) : ?>
                <?php $menu = Factory::getApplication()->getMenu(); ?>
                <?php $active = $menu->getActive(); ?>
                <?php $itemId = $active->id; ?>
                <?php $link = new Uri(Route::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false)); ?>
                <?php $link->setVar('return', base64_encode(RouteHelper::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language))); ?>
                <?php echo LayoutHelper::render('joomla.content.readmore', ['item' => $this->item, 'params' => $params, 'link' => $link]); ?>
            <?php endif; ?>
        <?php endif; ?>
        <?php
        if (!empty($this->item->pagination) && $this->item->paginationposition && $this->item->paginationrelative) :
            echo $this->item->pagination;
            ?>
        <?php endif; ?>

        <?php //Banner module position ?>
            <?php if (!empty($modsBanner)) : ?>
                <div class="content-bottom-banner py-3 my-4 border-top border-bottom border-light-subtle text-center">
                    <?php foreach ($modsBanner as $mod) : ?>
                        <div class="d-inline-block">
                            <?php echo ModuleHelper::renderModule($mod, ['style' => 'none']); ?>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

        <?php //Article module position ?>
        <?php if (!empty($mods)) : ?>
            <div class="content-bottom my-3">
                <?php foreach ($mods as $mod) : ?>
                    <?php echo ModuleHelper::renderModule($mod, ['style' => 'none']); ?>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>

        <?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
        <?php echo $this->item->event->afterDisplayContent; ?>
            </div>
        </div>
    </div>
</div>
